author: "William Welch <billywelch@gmail.com>"
description: "Fork of William Welch's driver, with updated crypto dependencies."
documentation: "https://github.com/billysometimes/rethinkdb"
homepage: "https://github.com/billysometimes/rethinkdb"
name: "rethinkdb"
version: "2.3.1"
dependencies: 
  crypto: "^2.0.0"
  protobuf: "^0.5.1+2"
dev_dependencies: 
  test: "^0.12.13+4"
environment: 
  sdk: ">=1.13.0 <2.0.0"
