name: rethinkdb_driver
version: 2.3.1
author: William Welch <billywelch@gmail.com>
description: Fork of William Welch's driver, with updated crypto dependencies.
homepage: https://github.com/billysometimes/rethinkdb
documentation: https://github.com/billysometimes/rethinkdb
environment:
  sdk: ">=1.13.0 <2.0.0"
dependencies:
  protobuf: "^0.5.1+2"
  crypto: "^2.0.0"
dev_dependencies:
  test: "^0.12.13+4"
